language: node_js
node_js:
  - 8
  - 10
cache:
  directories:
    - node_modules
script:
  - cd granasat_pm_client
  - npm install --save
  - npm test
  - npm cache clean
  - npm install --save
  - npm run-script build
